import React from "react";
import { motion } from "framer-motion";
import { ArrowRight } from "lucide-react";

const fadeUpVariants = {
  hidden: { opacity: 0, y: 30 },
    visible: {
        opacity: 1,
            y: 0,
                transition: {
                      duration: 0.8,
                            ease: [0.16, 1, 0.3, 1] as const,
                                },
                                  },
                                  };

                                  const staggerContainer = {
                                    hidden: { opacity: 0 },
                                      visible: {
                                          opacity: 1,
                                              transition: {
                                                    staggerChildren: 0.15,
                                                          delayChildren: 0.2,
                                                              },
                                                                },
                                                                };

                                                                const imageRevealVariants = {
                                                                  hidden: { opacity: 0, scale: 0.96 },
                                                                    visible: {
                                                                        opacity: 1,
                                                                            scale: 1,
                                                                                transition: {
                                                                                      duration: 1.2,
                                                                                            ease: [0.16, 1, 0.3, 1] as const,
                                                                                                },
                                                                                                  },
                                                                                                  };

                                                                                                  const BrandIntroduction: React.FC = () => {
                                                                                                    return (
                                                                                                        <section
                                                                                                              className="w-full bg-[#FAF8F5] py-20 md:py-28 lg:py-36 overflow-hidden"
                                                                                                                    aria-labelledby="brand-intro-heading"
                                                                                                                        >
                                                                                                                              <div className="max-w-[1440px] mx-auto px-6 md:px-12 lg:px-24">
                                                                                                                                      <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24 items-center">

                                                                                                                                                {/* Left Column */}
                                                                                                                                                          <motion.div
                                                                                                                                                                      className="w-full max-w-2xl mx-auto lg:mx-0 flex flex-col justify-center"
                                                                                                                                                                                  variants={staggerContainer}
                                                                                                                                                                                              initial="hidden"
                                                                                                                                                                                                          whileInView="visible"
                                                                                                                                                                                                                      viewport={{ once: true, margin: "-10%" }}
                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                            <motion.span
                                                                                                                                                                                                                                                          variants={fadeUpVariants}
                                                                                                                                                                                                                                                                        className="block text-[#B89146] font-medium tracking-[0.2em] text-[12px] md:text-[14px] uppercase mb-6"
                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                  Est. 2012 — By Preksha Chhajer
                                                                                                                                                                                                                                                                                                              </motion.span>

                                                                                                                                                                                                                                                                                                                          <motion.h2
                                                                                                                                                                                                                                                                                                                                        id="brand-intro-heading"
                                                                                                                                                                                                                                                                                                                                                      variants={fadeUpVariants}
                                                                                                                                                                                                                                                                                                                                                                    className="font-playfair text-[#1D1D1D] text-[36px] md:text-[44px] lg:text-[52px] leading-[1.15] mb-8 font-medium"
                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                              Moments. Memories. Magic.
                                                                                                                                                                                                                                                                                                                                                                                                          </motion.h2>

                                                                                                                                                                                                                                                                                                                                                                                                                      <motion.p
                                                                                                                                                                                                                                                                                                                                                                                                                                    variants={fadeUpVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="text-[#666666] text-[16px] md:text-[18px] leading-[1.8] mb-6 font-light"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            We transform beautiful ideas into unforgettable celebrations that
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          inspire awe and become lifelong memories. Every event is a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        canvas, and your vision is our masterpiece.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <motion.p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              variants={fadeUpVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="text-[#666666] text-[16px] md:text-[18px] leading-[1.8] mb-12 font-light"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      As a premier luxury event planner based in Kolkata, we specialize
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    in creating bespoke celebrations tailored to your unique desires,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  delivered with exceptional and uncompromising attention to detail.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.div variants={fadeUpVariants} className="inline-block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="group inline-flex items-center gap-3 text-[#1D1D1D] font-medium text-[15px] md:text-[16px] tracking-wide transition-all duration-300 hover:text-[#B89146] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#B89146] focus-visible:ring-offset-4 focus-visible:ring-offset-[#FAF8F5] rounded-sm pb-1 border-b border-[#1D1D1D]/30 hover:border-[#B89146]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        aria-label="Discover the story of MatchStick Events"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Discover Our Story

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ArrowRight
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-4 h-4 transition-transform duration-300 group-hover:translate-x-1.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          aria-hidden="true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Right Column */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full relative"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          variants={imageRevealVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      initial="hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  whileInView="visible"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              viewport={{ once: true, margin: "-10%" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="relative w-full aspect-[4/5] md:aspect-[3/4] lg:aspect-[4/5] max-w-xl mx-auto lg:max-w-none lg:ml-auto rounded-[24px] lg:rounded-[32px] overflow-hidden shadow-[0_20px_60px_rgba(0,0,0,0.06)] bg-[#E7E3DD]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  src="https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=2069&auto=format&fit=crop"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alt="Elegant wedding table setting representing bespoke celebrations"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loading="lazy"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoding="async"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  draggable={false}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full h-full object-cover object-center transition-transform duration-[2500ms] ease-out hover:scale-[1.03]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="absolute inset-0 border border-black/[0.04] rounded-[24px] lg:rounded-[32px] pointer-events-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aria-hidden="true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="absolute -bottom-8 -right-8 w-2/3 h-2/3 bg-[#B89146]/5 rounded-bl-[100px] rounded-tr-[100px] -z-10 hidden md:block"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                aria-hidden="true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default BrandIntroduction;