import React from 'react';
import { motion } from 'framer-motion';
import { 
  MessageCircle, 
    Lightbulb, 
      PencilRuler, 
        ClipboardCheck, 
          PartyPopper 
          } from 'lucide-react';

          // ============================================================================
          // TIMELINE DATA
          // ============================================================================
          const STEPS_DATA = [
            {
                id: 'step-1',
                    number: '01',
                        title: 'Initial Consultation',
                            description: 'We begin by listening to your ideas, preferences and the moments you want your celebration to create.',
                                Icon: MessageCircle,
                                  },
                                    {
                                        id: 'step-2',
                                            number: '02',
                                                title: 'Understanding Your Vision',
                                                    description: 'Together we explore your style, priorities and inspiration to shape a celebration that feels uniquely yours.',
                                                        Icon: Lightbulb,
                                                          },
                                                            {
                                                                id: 'step-3',
                                                                    number: '03',
                                                                        title: 'Concept & Planning',
                                                                            description: 'Layouts, themes, décor concepts and logistics come together into a clear creative direction.',
                                                                                Icon: PencilRuler,
                                                                                  },
                                                                                    {
                                                                                        id: 'step-4',
                                                                                            number: '04',
                                                                                                title: 'Design & Coordination',
                                                                                                    description: 'Trusted coordination and careful planning ensure every detail is thoughtfully prepared before the event.',
                                                                                                        Icon: ClipboardCheck,
                                                                                                          },
                                                                                                            {
                                                                                                                id: 'step-5',
                                                                                                                    number: '05',
                                                                                                                        title: 'Celebration Day',
                                                                                                                            description: 'Relax and enjoy every moment while everything comes together beautifully behind the scenes.',
                                                                                                                                Icon: PartyPopper,
                                                                                                                                  }
                                                                                                                                  ];

                                                                                                                                  // ============================================================================
                                                                                                                                  // ANIMATION VARIANTS
                                                                                                                                  // ============================================================================
                                                                                                                                  const staggerContainer = {
                                                                                                                                    hidden: { opacity: 0 },
                                                                                                                                      visible: {
                                                                                                                                          opacity: 1,
                                                                                                                                              transition: {
                                                                                                                                                    staggerChildren: 0.1,
                                                                                                                                                          delayChildren: 0.2,
                                                                                                                                                              }
                                                                                                                                                                }
                                                                                                                                                                };

                                                                                                                                                                const fadeUpVariant = {
                                                                                                                                                                  hidden: { opacity: 0, y: 30 },
                                                                                                                                                                    visible: { 
                                                                                                                                                                        opacity: 1, 
                                                                                                                                                                            y: 0, 
                                                                                                                                                                                transition: { 
                                                                                                                                                                                      duration: 0.8, 
                                                                                                                                                                                            ease: [0.16, 1, 0.3, 1] 
                                                                                                                                                                                                } 
                                                                                                                                                                                                  }
                                                                                                                                                                                                  };

                                                                                                                                                                                                  // ============================================================================
                                                                                                                                                                                                  // COMPONENT
                                                                                                                                                                                                  // ============================================================================
                                                                                                                                                                                                  const PlanningExperience: React.FC = () => {
                                                                                                                                                                                                    return (
                                                                                                                                                                                                        <section 
                                                                                                                                                                                                              id="planning-experience"
                                                                                                                                                                                                                    className="w-full bg-[#FAF8F5] py-24 md:py-32 overflow-hidden relative z-0"
                                                                                                                                                                                                                          aria-labelledby="planning-experience-heading"
                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                    <div className="max-w-[1440px] mx-auto px-6 md:px-12 lg:px-24">
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    {/* Section Header */}
                                                                                                                                                                                                                                                            <motion.header 
                                                                                                                                                                                                                                                                      className="max-w-3xl mx-auto text-center mb-16 md:mb-24"
                                                                                                                                                                                                                                                                                initial="hidden"
                                                                                                                                                                                                                                                                                          whileInView="visible"
                                                                                                                                                                                                                                                                                                    viewport={{ once: true, margin: "-10%" }}
                                                                                                                                                                                                                                                                                                              variants={staggerContainer}
                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                <motion.span 
                                                                                                                                                                                                                                                                                                                                            variants={fadeUpVariant}
                                                                                                                                                                                                                                                                                                                                                        className="block text-[#B89146] font-medium tracking-[0.2em] text-[12px] uppercase mb-4"
                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                              Our Process
                                                                                                                                                                                                                                                                                                                                                                                        </motion.span>
                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                            <motion.h2 
                                                                                                                                                                                                                                                                                                                                                                                                                        id="planning-experience-heading"
                                                                                                                                                                                                                                                                                                                                                                                                                                    variants={fadeUpVariant}
                                                                                                                                                                                                                                                                                                                                                                                                                                                className="font-playfair text-[#1D1D1D] text-[36px] md:text-[44px] lg:text-[48px] leading-[1.15] font-medium mb-6"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      From Vision to Celebration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.p 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                variants={fadeUpVariant}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="text-[#666666] font-inter text-[16px] md:text-[18px] leading-[1.7] font-light max-w-2xl mx-auto"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Bringing your personal story to life requires more than just careful logistics—it demands a shared vision. From our first conversation to the final memorable moments of your event, we guide you through a seamless, collaborative journey.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Timeline Container */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Desktop Connecting Line */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Positioned exactly behind the center of the icon containers (p-6/8 + h-12/2 = top offset) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="hidden lg:block absolute top-[56px] left-[5%] right-[5%] h-[1px] bg-gradient-to-r from-transparent via-[#B89146]/20 to-transparent -z-10" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aria-hidden="true" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Cards Grid */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <motion.div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6 lg:gap-5 relative z-10"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          initial="hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      whileInView="visible"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  viewport={{ once: true, margin: "-10%" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              variants={staggerContainer}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {STEPS_DATA.map((step) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <motion.article 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={step.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  variants={fadeUpVariant}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    group relative flex flex-col 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      bg-white rounded-[24px] 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border border-[#E7E3DD] 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          p-6 lg:p-8 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shadow-[0_4px_12px_rgba(0,0,0,0.02)] 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              hover:shadow-[0_18px_50px_rgba(0,0,0,0.08)] 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hover:border-[#B89146]/30
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hover:-translate-y-1.5 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transition-all duration-300 ease-out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      overflow-hidden
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Large Background Step Number */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="absolute -top-4 -right-2 text-[80px] md:text-[100px] font-playfair font-bold text-[#FAF8F5] leading-none pointer-events-none select-none transition-colors duration-300 group-hover:text-[#B89146]/[0.04]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        aria-hidden="true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {step.number}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Icon Container */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-12 h-12 rounded-full bg-[#FAF8F5] flex items-center justify-center mb-8 relative z-10 transition-colors duration-300 group-hover:bg-[#B89146]/10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <step.Icon 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-5 h-5 text-[#1D1D1D] transition-colors duration-300 group-hover:text-[#B89146]" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aria-hidden="true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        strokeWidth={1.5}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-playfair text-[#1D1D1D] text-[18px] lg:text-[20px] leading-[1.3] font-medium mb-3 relative z-10 transition-colors duration-300 group-hover:text-[#B89146]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {step.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-[#666666] font-inter text-[14px] leading-[1.65] font-light relative z-10 grow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {step.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default PlanningExperience;