import React from "react";
import { motion } from "framer-motion";
import { ArrowDown } from "lucide-react";

import Button from "../../components/ui/Button";

const Hero: React.FC = () => {
  const containerVariants = {
      hidden: { opacity: 0 },
          visible: {
                opacity: 1,
                      transition: {
                              staggerChildren: 0.2,
                                      delayChildren: 0.3,
                                            },
                                                },
                                                  };

                                                    const itemVariants = {
                                                        hidden: { opacity: 0, y: 20 },
                                                            visible: {
                                                                  opacity: 1,
                                                                        y: 0,
                                                                              transition: {
                                                                                      duration: 0.8,
                                                                                              ease: [0.16, 1, 0.3, 1] as const,
                                                                                                    },
                                                                                                        },
                                                                                                          };

                                                                                                            return (
                                                                                                                <section
                                                                                                                      className="relative h-[100dvh] min-h-[700px] w-full overflow-hidden flex items-center bg-[#1D1D1D]"
                                                                                                                            aria-label="Introduction"
                                                                                                                                >
                                                                                                                                      {/* Background Media */}
                                                                                                                                            <motion.div
                                                                                                                                                    initial={{ scale: 1.05, opacity: 0 }}
                                                                                                                                                            animate={{ scale: 1, opacity: 1 }}
                                                                                                                                                                    transition={{ duration: 1.2, ease: "easeOut" }}
                                                                                                                                                                            className="absolute inset-0 z-0"
                                                                                                                                                                                  >
                                                                                                                                                                                          <img
                                                                                                                                                                                                    src="https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=2098&auto=format&fit=crop"
                                                                                                                                                                                                              alt="Luxury event table setting with elegant floral arrangements"
                                                                                                                                                                                                                        className="w-full h-full object-cover object-center"
                                                                                                                                                                                                                                  loading="eager"
                                                                                                                                                                                                                                            fetchPriority="high"
                                                                                                                                                                                                                                                      draggable={false}
                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                      <div className="absolute inset-0 bg-gradient-to-t md:bg-gradient-to-r from-black/70 via-black/30 to-transparent mix-blend-multiply" />
                                                                                                                                                                                                                                                                              <div className="absolute inset-0 bg-black/10" />
                                                                                                                                                                                                                                                                                    </motion.div>

                                                                                                                                                                                                                                                                                          {/* Hero Content */}
                                                                                                                                                                                                                                                                                                <div className="relative z-10 w-full max-w-[1440px] mx-auto px-4 sm:px-6 md:px-12 lg:px-24 flex items-center h-full pt-16">
                                                                                                                                                                                                                                                                                                        <motion.div
                                                                                                                                                                                                                                                                                                                  variants={containerVariants}
                                                                                                                                                                                                                                                                                                                            initial="hidden"
                                                                                                                                                                                                                                                                                                                                      animate="visible"
                                                                                                                                                                                                                                                                                                                                                className="
                                                                                                                                                                                                                                                                                                                                                            max-w-[100%] sm:max-w-3xl lg:max-w-[840px]
                                                                                                                                                                                                                                                                                                                                                                        text-center md:text-left mx-auto md:mx-0
                                                                                                                                                                                                                                                                                                                                                                                    bg-white/[0.12] backdrop-blur-[24px] backdrop-saturate-[1.2]
                                                                                                                                                                                                                                                                                                                                                                                                border border-white/20
                                                                                                                                                                                                                                                                                                                                                                                                            rounded-[24px] md:rounded-[32px]
                                                                                                                                                                                                                                                                                                                                                                                                                        p-8 sm:p-10 md:p-12 lg:p-14
                                                                                                                                                                                                                                                                                                                                                                                                                                    shadow-[0_16px_40px_rgba(0,0,0,0.15)]
                                                                                                                                                                                                                                                                                                                                                                                                                                              "
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <motion.div variants={itemVariants} className="mb-6 md:mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-[#B89146] font-bold tracking-[0.25em] text-[12px] md:text-[14px] uppercase block [text-shadow:_0_2px_8px_rgba(0,0,0,0.4)]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Moments. Memories. Magic.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.h1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      variants={itemVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="font-playfair font-medium md:font-semibold text-[40px] sm:text-[48px] md:text-[56px] lg:text-[64px] text-white leading-[1.2] mb-6 md:mb-8 [text-shadow:_0_4px_12px_rgba(0,0,0,0.25)]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Every Celebration Deserves a{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br className="hidden lg:block" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="italic text-[#B89146]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Story Worth Remembering.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <motion.p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          variants={itemVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="text-[16px] md:text-[18px] text-white/95 leading-[1.8] max-w-2xl mx-auto md:mx-0 mb-10 md:mb-12 font-normal [text-shadow:_0_2px_8px_rgba(0,0,0,0.5)]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Transform beautiful ideas into unforgettable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bespoke celebrations that inspire awe.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Experience luxury event planning with
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          uncompromising attention to detail.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    variants={itemVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex flex-col sm:flex-row items-center justify-center md:justify-start gap-4 sm:gap-6"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button variant="primary" className="w-full sm:w-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Book Consultation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button variant="ghost" className="w-full sm:w-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Explore Our Work
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Scroll Indicator */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          animate={{ opacity: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transition={{ delay: 1.5, duration: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 z-10 select-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  aria-hidden="true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-[11px] text-white/80 tracking-[0.15em] uppercase font-semibold [text-shadow:_0_2px_4px_rgba(0,0,0,0.5)]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Scroll
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={{ y: [0, 8, 0] }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              transition={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      duration: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ease: "easeInOut",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ArrowDown className="w-5 h-5 text-[#B89146] drop-shadow-md" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Hero;